const {SUPABASE_URL,SUPABASE_KEY}=window.MODEX_CONFIG,REST=`${SUPABASE_URL}/rest/v1`;let session=JSON.parse(localStorage.getItem('modex_session')||'null'),ordersCache=[];
const loginView=document.getElementById('loginView'),adminView=document.getElementById('adminView');
function money(v){return new Intl.NumberFormat('uz-UZ').format(Number(v||0))+" so‘m"}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function request(url,options={},token=session?.access_token){const r=await fetch(url,{...options,headers:{apikey:SUPABASE_KEY,...(token?{Authorization:`Bearer ${token}`}:{Authorization:`Bearer ${SUPABASE_KEY}`}),...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}async function api(path,o={}){return request(`${REST}/${path}`,o)}
async function role(){const rows=await api(`profiles?select=role,name&id=eq.${session.user.id}&limit=1`);return rows?.[0]}
async function showAdmin(){try{const p=await role();if(p?.role!=='admin')throw new Error('admin emas');loginView.classList.add('hidden');adminView.classList.remove('hidden');adminEmail.textContent=session.user.email;loadAll()}catch{localStorage.removeItem('modex_session');session=null;showLogin();loginMessage.textContent='Bu akkaunt administrator emas.'}}
function showLogin(){loginView.classList.remove('hidden');adminView.classList.add('hidden')}
loginForm.onsubmit=async e=>{e.preventDefault();loginMessage.textContent='Kirilmoqda...';try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:email.value.trim(),password:password.value})});if(!r.ok)throw new Error(await r.text());session=await r.json();localStorage.setItem('modex_session',JSON.stringify(session));await showAdmin()}catch(err){loginMessage.textContent='Login, parol yoki admin huquqi noto‘g‘ri.';loginMessage.className='form-message error'}};
logoutBtn.onclick=()=>{localStorage.removeItem('modex_session');session=null;showLogin()};refreshBtn.onclick=loadAll;async function loadAll(){await Promise.all([loadOrders(),loadProductsAdmin(),loadOperators(),loadSupport()])}
async function loadOrders(){try{ordersCache=await api('orders?select=*&order=created_at.desc');renderOrders();aOrders.textContent=ordersCache.length;aNew.textContent=ordersCache.filter(o=>o.status==='new').length}catch(e){ordersMessage.textContent='Buyurtmalarni yuklab bo‘lmadi.'}}
function renderOrders(){const q=adminOrderSearch.value.toLowerCase();ordersBody.innerHTML='';ordersCache.filter(o=>`${o.name} ${o.surname||''} ${o.phone} ${o.product} ${o.region||''}`.toLowerCase().includes(q)).forEach(o=>ordersBody.insertAdjacentHTML('beforeend',`<tr><td>#${o.id}</td><td>${new Date(o.created_at).toLocaleString('uz-UZ')}</td><td>${esc(o.name)} ${esc(o.surname||'')}</td><td><a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></td><td>${esc(o.product)}</td><td>${esc(o.region||'-')}</td><td>${esc(o.utm_source||'sayt')}</td><td><span class="badge ${esc(o.status||'new')}">${esc(o.status||'new')}</span></td></tr>`))}adminOrderSearch.oninput=renderOrders;
async function uploadImage(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;await request(`${SUPABASE_URL}/storage/v1/object/product-images/${path}`,{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});return `${SUPABASE_URL}/storage/v1/object/public/product-images/${path}`}
productForm.onsubmit=async e=>{e.preventDefault();const m=productMessage,b=e.submitter;b.disabled=true;try{const image_url=await uploadImage(pImage.files[0]);await api('products',{method:'POST',headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({name:pName.value.trim(),category:pCategory.value.trim(),price:Number(pPrice.value),description:pDesc.value.trim(),image_url,active:true})});e.target.reset();m.textContent='Mahsulot qo‘shildi.';m.className='form-message success';loadProductsAdmin()}catch(err){m.textContent='Mahsulotni qo‘shib bo‘lmadi.';m.className='form-message error'}finally{b.disabled=false}};
async function loadProductsAdmin(){try{const ps=await api('products?select=id,name,price,image_url,category,active&order=id.desc');aProducts.textContent=ps.length;adminProducts.innerHTML='';ps.forEach(p=>{const el=document.createElement('div');el.className='product-admin-item';el.innerHTML=`<img src="${esc(p.image_url||'')}" alt=""><div><strong>${esc(p.name)}</strong><span>${esc(p.category||'')} · ${money(p.price)}</span><small class="target-link">product.html?id=${p.id}</small></div><button class="small-btn delete-product">O‘chirish</button>`;el.querySelector('button').onclick=async()=>{if(confirm('Mahsulot o‘chirilsinmi?')){await api(`products?id=eq.${p.id}`,{method:'DELETE'});loadProductsAdmin()}};adminProducts.appendChild(el)})}catch(e){console.error(e)}}
operatorCreateForm.onsubmit=async e=>{e.preventDefault();operatorCreateMessage.textContent='Yaratilmoqda...';try{const r=await fetch(`${SUPABASE_URL}/functions/v1/create-operator`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({name:opName.value.trim(),email:newOpEmail.value.trim(),password:newOpPassword.value})});if(!r.ok)throw new Error(await r.text());operatorCreateMessage.textContent='Operator yaratildi.';operatorCreateMessage.className='form-message success';e.target.reset();loadOperators()}catch(err){operatorCreateMessage.textContent='Operator yaratilmadi. Edge Function sozlanganini tekshiring.';operatorCreateMessage.className='form-message error'}};
async function loadOperators(){try{const ops=await api('profiles?select=id,name,role,active,created_at&role=eq.operator&order=created_at.desc');aOperators.textContent=ops.length;operatorsList.innerHTML=ops.map(o=>`<div class="support-item"><div><strong>${esc(o.name||'Operator')}</strong><span>${o.active?'Faol':'Bloklangan'}</span></div><button class="small-btn toggle-op" data-id="${o.id}" data-active="${o.active}">${o.active?'Bloklash':'Faollashtirish'}</button></div>`).join('');operatorsList.querySelectorAll('.toggle-op').forEach(b=>b.onclick=async()=>{await api(`profiles?id=eq.${b.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:b.dataset.active!=='true'})});loadOperators()})}catch(e){console.error(e)}}
async function loadSupport(){try{const xs=await api('support_requests?select=*&order=created_at.desc&limit=50');adminSupportList.innerHTML=xs.map(x=>`<div class="support-item"><div><strong>${esc(x.name)} · <a href="tel:${esc(x.phone)}">${esc(x.phone)}</a></strong><span>${esc(x.message)}</span></div><span class="badge">${esc(x.status||'new')}</span></div>`).join('')}catch(e){console.error(e)}}
if(session?.access_token)showAdmin();else showLogin();
