const {SUPABASE_URL,SUPABASE_KEY}=window.MODEX_CONFIG,REST=`${SUPABASE_URL}/rest/v1`;let session=JSON.parse(localStorage.getItem('modex_operator_session')||'null'),orders=[];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function request(url,options={}){const r=await fetch(url,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session?.access_token||SUPABASE_KEY}`,...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}async function api(path,o={}){return request(`${REST}/${path}`,o)}
async function getProfile(){const p=await api(`profiles?select=id,name,role,active&id=eq.${session.user.id}&limit=1`);return p?.[0]}
function showLogin(){operatorLogin.classList.remove('hidden');operatorView.classList.add('hidden')}
async function showOperator(){try{const p=await getProfile();if(p?.role!=='operator'||p?.active===false)throw new Error();operatorLogin.classList.add('hidden');operatorView.classList.remove('hidden');opEmailView.textContent=session.user.email;loadAll()}catch{localStorage.removeItem('modex_operator_session');session=null;showLogin();opLoginMessage.textContent='Operator akkaunti faol emas.'}}
operatorLoginForm.onsubmit=async e=>{e.preventDefault();try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:opEmail.value.trim(),password:opPassword.value})});if(!r.ok)throw new Error();session=await r.json();localStorage.setItem('modex_operator_session',JSON.stringify(session));showOperator()}catch{opLoginMessage.textContent='Login yoki parol noto‘g‘ri.';opLoginMessage.className='form-message error'}};
opLogout.onclick=()=>{localStorage.removeItem('modex_operator_session');session=null;showLogin()};opRefresh.onclick=loadAll;async function loadAll(){await Promise.all([loadOrders(),loadSupport()])}
async function loadOrders(){try{orders=await api('orders?select=*&order=created_at.desc');operatorOrders.innerHTML='';orders.forEach(o=>{const tr=document.createElement('tr');tr.innerHTML=`<td>#${o.id}</td><td>${new Date(o.created_at).toLocaleString('uz-UZ')}</td><td>${esc(o.name)} ${esc(o.surname||'')}</td><td><a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></td><td>${esc(o.product)}</td><td><span class="badge ${esc(o.status||'new')}">${esc(o.status||'new')}</span></td><td><button class="small-btn edit-btn">Ochish</button></td>`;tr.querySelector('button').onclick=()=>openEdit(o);operatorOrders.appendChild(tr)});statNew.textContent=orders.filter(o=>o.status==='new').length;statCalled.textContent=orders.filter(o=>o.status==='called').length;statConfirmed.textContent=orders.filter(o=>o.status==='confirmed').length}catch(e){operatorMessage.textContent='Zayavkalarni yuklab bo‘lmadi.'}}
function openEdit(o){editId.value=o.id;editOrderTitle.textContent=`Buyurtma #${o.id}`;editName.value=o.name||'';editSurname.value=o.surname||'';editPhone.value=o.phone||'';editRegion.value=o.region||'';editAddress.value=o.address||'';editNote.value=o.note||'';editStatus.value=o.status||'new';editMessage.textContent='';orderEditDialog.showModal()}
closeOrderEdit.onclick=()=>orderEditDialog.close();orderEditForm.onsubmit=async e=>{e.preventDefault();try{await api(`orders?id=eq.${encodeURIComponent(editId.value)}`,{method:'PATCH',headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({name:editName.value.trim(),surname:editSurname.value.trim(),phone:editPhone.value.trim(),region:editRegion.value.trim(),address:editAddress.value.trim(),note:editNote.value.trim(),status:editStatus.value,operator_id:session.user.id})});editMessage.textContent='Saqlandi.';editMessage.className='form-message success';await loadOrders()}catch(e){editMessage.textContent='Saqlab bo‘lmadi.';editMessage.className='form-message error'}};
printQrBtn.onclick=async()=>{const o=orders.find(x=>String(x.id)===String(editId.value));if(!o)return;if(!o.public_token){editMessage.textContent='QR token yo‘q. setup.sql ni qayta ishga tushiring.';return}const url=`${location.origin}${location.pathname.replace('operator.html','order.html')}?t=${encodeURIComponent(o.public_token)}`;printArea.innerHTML=`<div class="label-card"><strong>MODEX.UZ</strong><div>Buyurtma #${o.id}</div><div>${esc(editName.value)} ${esc(editSurname.value)}</div><div>${esc(editRegion.value||'')}</div><div id="qrBox"></div></div>`;new QRCode(document.getElementById('qrBox'),{text:url,width:150,height:150});setTimeout(()=>window.print(),250)};
async function loadSupport(){try{const xs=await api('support_requests?select=*&order=created_at.desc&limit=30');supportList.innerHTML=xs.map(x=>`<div class="support-item"><div><strong>${esc(x.name)} · <a href="tel:${esc(x.phone)}">${esc(x.phone)}</a></strong><span>${esc(x.message)}</span></div></div>`).join('')}catch(e){console.error(e)}}
if(session?.access_token)showOperator();else showLogin();
