-- MODEX.UZ V2 migration / setup
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Existing tables: add new fields safely
alter table public.products add column if not exists category text;
alter table public.orders add column if not exists product_id bigint;
alter table public.orders add column if not exists surname text;
alter table public.orders add column if not exists region text;
alter table public.orders add column if not exists address text;
alter table public.orders add column if not exists note text;
alter table public.orders add column if not exists operator_id uuid;
alter table public.orders add column if not exists utm_source text;
alter table public.orders add column if not exists utm_campaign text;
alter table public.orders add column if not exists utm_content text;
alter table public.orders add column if not exists public_token uuid default gen_random_uuid();
update public.orders set public_token=gen_random_uuid() where public_token is null;
alter table public.orders alter column public_token set default gen_random_uuid();

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  role text not null default 'pending' check (role in ('admin','operator','pending')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.support_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  message text not null,
  status text not null default 'new'
);

-- Automatically create a harmless pending profile for new Auth users.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,name,role,active)
  values(new.id,coalesce(new.raw_user_meta_data->>'name',''),'pending',true)
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Role helpers avoid recursive RLS checks.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and active=true);
$$;
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','operator') and active=true);
$$;
revoke all on function public.is_admin() from public;
revoke all on function public.is_staff() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_staff() to authenticated;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.profiles enable row level security;
alter table public.support_requests enable row level security;

-- Products
DROP POLICY IF EXISTS "products_public_read" ON public.products;
DROP POLICY IF EXISTS "products_admin_all" ON public.products;
create policy "products_public_read" on public.products for select to anon,authenticated using (active=true or public.is_admin());
create policy "products_admin_all" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Orders: visitor may submit. Only active staff may read/update.
DROP POLICY IF EXISTS "orders_public_insert" ON public.orders;
DROP POLICY IF EXISTS "orders_staff_read" ON public.orders;
DROP POLICY IF EXISTS "orders_staff_update" ON public.orders;
DROP POLICY IF EXISTS "orders_admin_delete" ON public.orders;
create policy "orders_public_insert" on public.orders for insert to anon,authenticated with check (true);
create policy "orders_staff_read" on public.orders for select to authenticated using (public.is_staff());
create policy "orders_staff_update" on public.orders for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "orders_admin_delete" on public.orders for delete to authenticated using (public.is_admin());

-- Profiles: a user can read own profile. Admin can manage all.
DROP POLICY IF EXISTS "profiles_own_read" ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_read" ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_update" ON public.profiles;
create policy "profiles_own_read" on public.profiles for select to authenticated using (id=auth.uid());
create policy "profiles_admin_read" on public.profiles for select to authenticated using (public.is_admin());
create policy "profiles_admin_update" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Support
DROP POLICY IF EXISTS "support_public_insert" ON public.support_requests;
DROP POLICY IF EXISTS "support_staff_read" ON public.support_requests;
DROP POLICY IF EXISTS "support_staff_update" ON public.support_requests;
create policy "support_public_insert" on public.support_requests for insert to anon,authenticated with check (true);
create policy "support_staff_read" on public.support_requests for select to authenticated using (public.is_staff());
create policy "support_staff_update" on public.support_requests for update to authenticated using (public.is_staff()) with check (public.is_staff());

-- QR lookup: only a long random token is accepted. Phone is not placed inside QR itself.
create or replace function public.get_order_phone(p_token uuid)
returns table(full_name text, region text, phone text)
language sql stable security definer set search_path=public as $$
  select trim(concat_ws(' ',o.name,o.surname)), o.region, o.phone
  from public.orders o where o.public_token=p_token limit 1;
$$;
revoke all on function public.get_order_phone(uuid) from public;
grant execute on function public.get_order_phone(uuid) to anon,authenticated;

-- Storage policies for product-images bucket (bucket itself should be public).
insert into storage.buckets(id,name,public) values('product-images','product-images',true)
on conflict(id) do update set public=true;
DROP POLICY IF EXISTS "product_images_public_read" ON storage.objects;
DROP POLICY IF EXISTS "product_images_admin_insert" ON storage.objects;
DROP POLICY IF EXISTS "product_images_admin_update" ON storage.objects;
DROP POLICY IF EXISTS "product_images_admin_delete" ON storage.objects;
create policy "product_images_public_read" on storage.objects for select to public using (bucket_id='product-images');
create policy "product_images_admin_insert" on storage.objects for insert to authenticated with check (bucket_id='product-images' and public.is_admin());
create policy "product_images_admin_update" on storage.objects for update to authenticated using (bucket_id='product-images' and public.is_admin());
create policy "product_images_admin_delete" on storage.objects for delete to authenticated using (bucket_id='product-images' and public.is_admin());

-- IMPORTANT: after running this file, promote YOUR existing Auth user to admin once:
-- insert into public.profiles(id,name,role,active)
-- values('YOUR_AUTH_USER_UUID','Asad','admin',true)
-- on conflict(id) do update set role='admin', active=true;
